### PR TITLE
Added support to nullsafety

### PR DESCRIPTION
**Pull request by andersonfds**
# Motivation

This plugin is beautiful! It deserves to be updated to the nowadays standards.

# Description

- Added support to nullsafety
- Changed dart minimum version to 2.12
- Changed example project to nullsafety too
- Edited the changelog

# Checks

- [x] Did you test your feature?
- [x] Did it worked both on Android and iOS?

### CODE REVIEW

**Comment by furkantektas** [comment]
Hi Anderson 👋🏻,
Thank you very much, this is quite an improvement and maintenance for the repo. All the changes seems good to me, please give me some time as I still need to merge another PR which I couldn't merge for quite a long time. I'll sort this out as soon as I can. 
Thanks

**Comment by andersonfds** [comment]
> Hi Anderson 👋🏻, Thank you very much, this is quite an improvement and maintenance for the repo. All the changes seems good to me, please give me some time as I still need to merge another PR which I couldn't merge for quite a long time. I'll sort this out as soon as I can. Thanks

Sure, no problem. If there is any merge conflicts with the other pull requests, just let me know and I'll fix

**Comment by furkantektas** [comment]
I really appreciate it, thank you very much

**Comment by furkantektas** [comment]
Hi @andersonfds ,
I have merged #9 today and resolved the conflicts with this PR afterwards. I wish I wrote some tests for this library, but, unfortunately, I didn't. That's why, I did a quick test with the example application, seems like it doesn't break anything. 
I will bump the version 0.1.0 with your contribution.
Thank you very much for your time and effort.

**Pull request merged**
